# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
# Unable to inspect table 'alternative_medium'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'alternative_medium_track'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'alternative_release'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'alternative_release_type'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'alternative_track'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'annotation'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'application'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'apps'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area_alias'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area_alias_type'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area_annotation'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area_attribute'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area_attribute_type'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area_attribute_type_allowed_value'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area_gid_redirect'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area_tag'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area_tag_raw'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'area_type'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'artist'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'artist_alias'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'artist_alias_type'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'artist_annotation'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'artist_attribute'
# The error was: sequence index must be integer, not 'slice'
