# Generated by Django 2.2.3 on 2019-08-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Artist2',
        ),
    ]
