# Generated by Django 2.1.7 on 2019-07-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='area',
            new_name='areas',
        ),
    ]
