# Generated by Django 2.1.7 on 2019-07-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Artist')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, through='lab.ArtistWork', to='lab.Artist'),
        ),
    ]
