# Generated by Django 2.1.7 on 2019-07-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='artists',
            field=models.ManyToManyField(through='lab.ArtistWork', to='lab.Artist'),
        ),
    ]
