# Generated by Django 2.2.3 on 2019-07-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20190716_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={},
        ),
        migrations.RenameField(
            model_name='work',
            old_name='artists',
            new_name='artist',
        ),
    ]
