# Generated by Django 2.2.3 on 2019-08-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20190801_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist2',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='type',
            new_name='type2',
        ),
    ]
