# Generated by Django 2.2.3 on 2019-07-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20190717_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='artist',
        ),
    ]
