# Generated by Django 2.1.7 on 2019-07-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20190716_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='gender',
        ),
        migrations.AddField(
            model_name='artist',
            name='genders',
            field=models.ForeignKey(blank=True, db_column='gender', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Gender'),
        ),
    ]
