# Generated by Django 2.2.3 on 2019-07-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_remove_work_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='artists',
            field=models.ManyToManyField(through='lab.ArtistWork', to='lab.Artist'),
        ),
    ]
