# Generated by Django 2.2.3 on 2019-07-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_work_artists'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artistwork',
            table='artistwork',
        ),
    ]
