# Generated by Django 2.2.3 on 2019-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20190718_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistwork',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
