# Generated by Django 2.2.3 on 2019-07-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_auto_20190718_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistwork',
            old_name='category',
            new_name='categorys',
        ),
    ]
