# Generated by Django 2.2.3 on 2019-07-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20190718_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistwork',
            old_name='categorys',
            new_name='category',
        ),
    ]
