# Generated by Django 2.2.3 on 2019-07-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20190718_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistwork',
            name='category',
        ),
    ]
