# Generated by Django 2.2.3 on 2019-07-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_remove_artistwork_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistwork',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
