# Generated by Django 2.2.3 on 2019-07-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_artistwork_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistwork',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
